### ISSUE TITLE
[BUG] Infinite reload caused by "CSP issues detected"

### ISSUE THREAD

**Issue by klinyecviktor** [scaljeri/oh-my-mock#134]
### Description
This extension causes infinite reload of some pages. 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14149402/163985008-32db6ee9-5d1b-4dc7-a4c9-f46ee5007d1f.png">

### Details
- Chrome extension version: 3.3.9
- Chrome version: 100.0.4896.127 (Official build), (arm64)

### Step to reproduce:
1. Go to page https://aws.amazon.com/ru/cloudsearch/developer-resources/
2. See that page reloads infinitely.

_Note:_ Oh-my-mock is not enabled on that page. Enabling it still causes the page to reload.

**Oh-my-mock logs:**
`(^*^) OhMyMock CSP issues detected, this page will be reloaded so CSP headers can be removed!`

**Comment by scaljeri** [comment]
Thanks for the bug report. The whole CSP implementation was a bit buggy. Next release will contain a fix for this!

**Comment by scaljeri** [comment]
3.3.10 is out. Can you confirm that everything is working again?

**Comment by klinyecviktor** [comment]
Hey @scaljeri 
Yeap, it works!
Many thanks!
