### ISSUE TITLE
Add custom names for the requests

### ISSUE THREAD

**Issue by miguelms95** [scaljeri/oh-my-mock#136]
Hi, first of all thanks for the development of the extension, it's awesome!

It would be great to have an option to add a name/tag to the requests and display in the table, because in some requests with a long url (with encrypted params, etc...) the last part of the url is hidden.

Maybe a new column:
* Type
* Method
* **Tag** <- this one empty by default, with option to write an string
* Url
* Response
* Actions

Sample: in this case we cannot differentiate the requests (same starting string, but endpoint difference is after the encoded string), and with the column would be easier to identify each one.
![image (2)](https://user-images.githubusercontent.com/17082987/164491676-d1b54a57-d668-4ea0-8cb9-087647a4ff2b.png)

**Comment by scaljeri** [comment]
Hi Miguel, yes this is indeed an issue. I was thinking about doing the ellipsis in the middle, so you will always see the beginning and the end. I guess that this will solve your issue, right?

But there is already one way you can handle this, you can use the `name` field for this:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/1078741/164498979-e28d98f8-cbac-4699-a4a0-3b6751204cfa.png">

If you provide this field, it will show up in the list:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1078741/164499158-bf9f97f0-9802-4df8-bc05-79d46642c1ae.png">

Will this help in your case?

**Comment by miguelms95** [comment]
Hi @scaljeri, thanks for the quick reply! The ellipsis in the middle would solve my issue.

The label helps in my case, that was actually what I was looking for, thanks!

**Comment by scaljeri** [comment]
nice, good luck and I'll try to add the ellipsis in the next release!
