### ISSUE TITLE
"Select all" on JSON export

### ISSUE THREAD

**Issue by miguelms95** [scaljeri/oh-my-mock#140]
It would be great to have a "select all" button in exporting JSON process, to step-over clicking every request

**Comment by scaljeri** [comment]
Hi Miguel, you actually can already do that

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1078741/172839214-3cdecaec-e406-4632-a9e1-9a7eb51cf5d2.png">


Is this what you mean?

**Comment by miguelms95** [comment]
Hi @scaljeri, yes, that was what I was looking for. I didn't find the icon descriptive. Maybe you can use: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aformat_list_bulleted%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048 or this other one: https://fontawesome.com/icons/list?s=solid Thanks!

**Comment by scaljeri** [comment]
Thnx for the suggestion! I do realise that many things are not that intuitive. There are plans to have a designer/ux-er check the app and make improvements
